### ISSUE TITLE
Issue with hibernate-memcached 1.4-SNAPSHOT and spymemcached 2.7.3

### ISSUE THREAD

**Issue by mcgrealc** [raykrueger/hibernate-memcached#16]
We ran into a problem with a branch build for a production service where the most up to date hibernate-memcached and spymemcached is failing to deploy:

https://gist.github.com/mcgrealc/3bcafe3791d56ba3f67c

To fix we have had to patch the old hibernate-memcached jar (prior to the changes made 24th March 2015) to the deployment.

Anyone else seeing the same issue?

**Comment by raykrueger** [comment]
Looks like they removed a class in the newer spy client. Send a pull request if you find a patch needed!

-Ray

**Comment by mcgrealc** [comment]
Not sure if thats our problem - we're still using spymemcached 2.7.3 however our gradle build pulled in a newer hibernate-memcached 1.4-SNAPSHOT jar which we've confirmed is different from the currently deployed (prior to 24th March 2015 commit) 1.4-SNAPSHOT jar.

**Comment by raykrueger** [comment]
Google code is going away and I worked on publishing a new jar to maven central. I published the same code at least that was the intent.

Take a look at the poms on central vs the sill svn thing I set up. Are the declaring different versions of the spy memcached dependency maybe?

-Ray
